#!/usr/bin/env python3
"""Prepare or verify one passive package from a full local source commit; never publish."""
import argparse
import hashlib
import json
from pathlib import Path
import posixpath
import re
import subprocess
import tomllib
from urllib.parse import unquote, urlsplit

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = "packages/development-governance"
HISTORICAL_PACKAGE = "vibevm/vibepacks/org.jresearch.ai/development-governance/v0.1.0"
REPOSITORY = "https://github.com/jresearchsoftware/shared-governance"
COORDINATE = "org.jresearch.ai/development-governance"
RECEIPT = "DISTRIBUTION.json"
PROTOCOL = "vibevm/vibespecs/protocols/proportional-controls.md"
VERSIONING = "vibevm/vibespecs/protocols/package-versioning.md"
AUTHORITY = "vibevm/vibespecs/protocols/requirement-authority.md"
BOOT_INDEX = "vibevm/vibespecs/boot/INDEX.md"
# Exact ordinary AGENTS contribution emitted by the pinned VibeVM 1.0.7 probe.
BOOT_BLOCK = '''<vibevm>
<!-- Generated by vibe — do not edit inside this block; it is rewritten on `vibe install`. Text outside the <vibevm> markers is yours. -->

# Session boot

This project's boot sequence is computed by vibe (the PROP-009 loading
model). To begin a session, read these files in order:

1. `vibevm/vibespecs/boot/STATIC.md` — if it exists. The static (priority) lane: read it
   first and in full.
2. `vibevm/vibespecs/boot/INDEX.md` — a generated TOML manifest. Read every file named
   by its `[[entry]]` tables, in the listed order. A `kind = "static"`
   entry is read directly; a `kind = "dynamic"` entry is an INCLUDE
   resolved at boot, and one carrying a `when` condition is read only when
   that condition holds for the current session.

Boot is pure file-reading — there is nothing to execute.
</vibevm>'''


def vibe_hash(files):
    """Pinned VibeVM 1.0.7 legacy tree recipe, for this bounded UTF-8 file set."""
    digest = hashlib.sha256()
    for name in sorted(files, key=lambda name: Path(name).parts):
        digest.update(name.encode() + b"\0" + files[name] + b"\0")
    return "sha256:" + digest.hexdigest()


def git(*args):
    return subprocess.check_output(["git", *args], cwd=ROOT)


def validate_skill_links(files, prefix):
    """Keep passive Markdown references within the selected export (also legacy Skills)."""
    for name, data in files.items():
        if not name.startswith(prefix + "/"):
            continue
        prose = re.sub(r"^```[^\n]*\n.*?^```\s*$", "", data.decode(), flags=re.M | re.S)
        targets = re.findall(r"\[[^\]\n]*\]\(\s*(<[^>\n]*>|[^)\s]+)", prose)
        targets += re.findall(r"^ {0,3}\[[^\]\n]+\]:\s*(<[^>\n]*>|[^\s]+)", prose, flags=re.M)
        for target in targets:
            url = urlsplit(target.strip("<>"))
            if url.scheme or url.netloc:
                continue
            resolved = posixpath.normpath(posixpath.join(posixpath.dirname(name), unquote(url.path))) if url.path else name
            if not resolved.startswith(prefix + "/") or resolved not in files:
                raise ValueError("passive payload has an escaping or missing local reference: " + name)


def slot(version):
    return "vibevm/vibedeps/org.jresearch.ai.development-governance/" + version


def package_path(revision):
    members = tomllib.loads(git("show", revision + ":vibe.toml").decode())["workspace"]["members"]
    if members not in ([PACKAGE], [HISTORICAL_PACKAGE]):
        raise ValueError("source has no supported single package authoring path")
    return members[0]


def validate_payload(files, license_bytes, historical=False):
    """Bound this repository's passive flow; historical exports retain their old shape."""
    for data in files.values():
        data.decode("utf-8")
    if "vibe.toml" not in files or "LICENSE" not in files:
        raise ValueError("source commit has no complete package")
    manifest = tomllib.loads(files["vibe.toml"].decode())
    package = manifest.get("package", {})
    if not isinstance(package, dict):
        raise ValueError("source package metadata must be a table")
    expected = {"group": "org.jresearch.ai", "name": "development-governance",
                "kind": "flow", "format": "simple", "epoch": 1,
                "publish": False, "frozen": True, "license": "MIT"}
    if any(type(package.get(key)) is not type(value) or package.get(key) != value
           for key, value in expected.items()):
        raise ValueError("source package identity/passivity/publication boundary differs")
    if set(manifest) != {"package", "boot_snippet"}:
        raise ValueError("unexpected package capability or dependency")
    version = package.get("version")
    if not isinstance(version, str) or not re.fullmatch(r"(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)", version):
        raise ValueError("package must have a release SemVer version")
    if historical and version != "0.1.0":
        raise ValueError("historical frozen package version differs")
    if set(package) - (set(expected) | {"description", "version"}):
        raise ValueError("unexpected package metadata")
    boot = {"source": "vibevm/vibespecs/boot/development-governance.md",
            "category": "flow", "link": "dynamic"}
    if manifest["boot_snippet"] != boot:
        raise ValueError("package boot declaration differs")
    allowed = {"vibe.toml", "LICENSE", "README.md", boot["source"], PROTOCOL}
    if not historical:
        allowed.add(VERSIONING)
    # Earlier full-commit exports retain their accepted one/two-protocol shapes.
    if tuple(map(int, version.split("."))) >= (1, 1, 0):
        allowed.add(AUTHORITY)
    if set(files) != allowed:
        raise ValueError("source package file set differs from declared passive payload")
    if files["LICENSE"] != license_bytes:
        raise ValueError("source/package license notices differ")
    validate_skill_links(files, "vibevm/vibespecs")
    protocols = allowed & {PROTOCOL, VERSIONING, AUTHORITY}
    if any(not files[name].strip() for name in protocols):
        raise ValueError("canonical protocol is empty")
    return manifest


def snapshot(revision):
    # Full commits make preparation stable even when source branches/tags move.
    if not re.fullmatch(r"[0-9a-f]{40}", revision):
        raise ValueError("--source-ref must be a full 40-character source commit SHA")
    resolved = git("rev-parse", "--verify", revision + "^{commit}").decode().strip()
    if resolved != revision:
        raise ValueError("source commit identity differs")
    package_root = package_path(revision)
    files = {}
    for entry in git("ls-tree", "-rz", revision, "--", package_root).split(b"\0"):
        if not entry:
            continue
        metadata, name = entry.split(b"\t", 1)
        mode, kind, oid = metadata.decode().split()
        relative = Path(name.decode()).relative_to(package_root).as_posix()
        if mode != "100644" or kind != "blob":
            raise ValueError("package contains a non-ordinary file: " + relative)
        files[relative] = git("cat-file", "blob", oid)
    manifest = validate_payload(files, git("show", revision + ":LICENSE"), package_root == HISTORICAL_PACKAGE)
    hashes = {name: hashlib.sha256(data).hexdigest() for name, data in sorted(files.items())}
    # Hash the sorted path/hash map, binding both file names and file bytes.
    content = hashlib.sha256(json.dumps(hashes, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
    receipt = {"schema": 1, "source_repository": REPOSITORY, "source_revision": revision,
               "source_path": package_root, "package": COORDINATE, "version": manifest["package"]["version"],
               "payload_sha256": content, "sha256": hashes}
    files[RECEIPT] = (json.dumps(receipt, indent=2, sort_keys=True) + "\n").encode()
    return files, receipt


def prepare(revision, destination):
    files, receipt = snapshot(revision)  # Validate before creating any output.
    destination = Path(destination)
    if destination.is_symlink() or destination.resolve().is_relative_to(ROOT):
        raise ValueError("distribution destination must be outside the authoring checkout, not a symlink")
    if destination.exists() and (not destination.is_dir() or any(destination.iterdir())):
        raise ValueError("destination must be absent or empty; distribution is not overwritten")
    destination.mkdir(parents=True, exist_ok=True)
    for relative, data in files.items():
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
    return receipt


def verify(revision, directory, installed=False):
    # Rebuild expectations from canonical Git, never trust a co-located receipt alone.
    files, receipt = snapshot(revision)
    directory = Path(directory)
    if directory.is_symlink() or not directory.is_dir():
        raise ValueError("distribution must be an ordinary directory")
    actual = set()
    for path in directory.rglob("*"):
        relative = path.relative_to(directory).as_posix()
        if relative == ".git" or relative.startswith(".git/"):
            continue
        if path.is_symlink():
            raise ValueError("distribution contains a symlink: " + relative)
        if path.is_file():
            actual.add(relative)
        elif not path.is_dir():
            raise ValueError("distribution contains a non-ordinary file: " + relative)
    if installed:
        actual.discard(".vibe-slot.toml")
        marker = tomllib.loads((directory / ".vibe-slot.toml").read_text())
        entries = [{"path": name, "sha256": hashlib.sha256(data).hexdigest()}
                   for name, data in sorted(files.items())]
        if (set(marker) != {"schema", "source_hash", "spec_format", "file"}
                or marker["schema"] != 1 or marker["spec_format"] != "mixed"
                or marker["source_hash"] != vibe_hash(files) or marker["file"] != entries):
            raise ValueError("installed slot metadata differs from canonical source identity")
    if actual != set(files):
        raise ValueError("distribution file set differs; missing=" + repr(sorted(set(files) - actual))
                         + "; extra=" + repr(sorted(actual - set(files))))
    for relative, expected in files.items():
        if (directory / relative).read_bytes() != expected:
            raise ValueError("distribution bytes differ: " + relative)
    return receipt


def verify_consumer(revision, directory):
    directory = Path(directory)
    files, receipt = snapshot(revision)
    version = receipt["version"]
    slot_path = slot(version)
    verify(revision, directory / slot_path, installed=True)
    manifest = tomllib.loads((directory / "vibe.toml").read_text())
    requires = manifest.get("requires", {})
    packages = requires.get("packages", {}) if isinstance(requires, dict) else None
    requirement = packages.get(COORDINATE) if isinstance(packages, dict) else None
    if (not isinstance(requirement, dict) or requirement.get("version") != "=" + version
            or not isinstance(requirement.get("git"), str) or not requirement["git"]
            or bool(requirement.get("tag")) == bool(requirement.get("rev"))
            or requirement.get("branch")):
        raise ValueError("consumer must declare exact-version Git tag/rev requirement")
    if (requirement.get("rev") and (not isinstance(requirement["rev"], str)
                                   or not re.fullmatch(r"[0-9a-f]{40}", requirement["rev"]))):
        raise ValueError("consumer Git revision must be a full commit SHA")
    lock = tomllib.loads((directory / "vibe.lock").read_text())
    meta = lock.get("meta")
    if not isinstance(meta, dict) or type(meta.get("schema_version")) is not int or meta["schema_version"] != 7:
        raise ValueError("consumer lock must use pinned VibeVM schema 7")
    locked = lock.get("package", [])
    if not isinstance(locked, list) or any(not isinstance(entry, dict) for entry in locked):
        raise ValueError("consumer lock packages must be tables")
    packages = [entry for entry in locked if
                entry.get("group") == "org.jresearch.ai" and entry.get("name") == "development-governance"]
    if len(packages) != 1:
        raise ValueError("consumer lock has no unique package identity")
    entry = packages[0]
    if any(entry.get(key) != value for key, value in {
            "version": version, "source_kind": "git", "source_url": requirement["git"],
            "source_ref": requirement.get("rev") or requirement["tag"], "content_hash": vibe_hash(files)}.items()):
        raise ValueError("consumer lock differs from canonical content/source declaration")
    # The removed package Skill and its native receipt must not remain active.
    for relative in (".agents/skills/proportional-controls",
                     ".agents/skills/.proportional-controls.vibe-skill-receipt.toml"):
        if (directory / relative).exists() or (directory / relative).is_symlink():
            raise ValueError("consumer retains the removed native Skill: " + relative)
    index = directory / BOOT_INDEX
    agents = directory / "AGENTS.md"
    if any(path.is_symlink() or not path.is_file() for path in (index, agents)):
        raise ValueError("consumer generated boot route must use ordinary files")
    boot = tomllib.loads(index.read_text(encoding="utf-8"))
    package_boot = slot_path + "/vibevm/vibespecs/boot/development-governance.md"
    entries = boot.get("entry", [])
    if (type(boot.get("schema")) is not int or boot["schema"] != 1 or not isinstance(entries, list)
            or any(not isinstance(e, dict) or not isinstance(e.get("path"), str) for e in entries)):
        raise ValueError("consumer boot index differs from pinned schema")
    selected = [e for e in entries if posixpath.normpath(e["path"]).startswith(slot_path + "/")]
    # Pinned upstream emits static despite the authored link=dynamic. Qualify it honestly.
    if selected != [{"path": package_boot, "kind": "static"}]:
        raise ValueError("consumer boot index has no unique canonical package route")
    blocks = re.findall(r"<vibevm>.*?</vibevm>", agents.read_text(encoding="utf-8"), flags=re.S)
    if blocks != [BOOT_BLOCK]:
        raise ValueError("consumer AGENTS does not route through the generated boot index")
    return receipt


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-ref", required=True, help="full source commit; acceptance is verified by its owner")
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--destination", type=Path, help="new/empty directory outside this authoring checkout")
    action.add_argument("--verify", type=Path, metavar="DIRECTORY", help="compare prepared bytes with canonical source")
    action.add_argument("--verify-installed", type=Path, metavar="DIRECTORY", help="also validate VibeVM's generated slot receipt")
    action.add_argument("--verify-consumer", type=Path, metavar="DIRECTORY", help="validate manifest, lock, installed bytes and absence of the removed native Skill")
    args = parser.parse_args()
    try:
        if args.destination is not None:
            receipt = prepare(args.source_ref, args.destination)
        elif args.verify_consumer:
            receipt = verify_consumer(args.source_ref, args.verify_consumer)
        else:
            receipt = verify(args.source_ref, args.verify or args.verify_installed, bool(args.verify_installed))
    except (ValueError, KeyError, OSError, subprocess.CalledProcessError) as error:
        parser.exit(1, "Distribution validation failed: " + str(error) + "\n")
    print(json.dumps({"distribution": "PASS", "action": "prepare" if args.destination else "verify",
                      "source_revision": receipt["source_revision"],
                      "payload_sha256": receipt["payload_sha256"], "files": len(receipt["sha256"]),
                      "publication": "this command never publishes; acceptance/remote authority are external"}))


if __name__ == "__main__":
    main()
